Models/Bikes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DublinBikes_Macintosh.Models
{
    public class Bikes
    {

        public int Id { get; set; }

        [Required]
        [Range(0, 200)]
        public int Number { get; set; }

        [Required]
        [StringLength(25, MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [StringLength(80, MinimumLength = 3)]
        public string Address { get; set; }

        [Required]
        [Range(-90, 90)]
        public double Latitude { get; set; }

        [Required]
        [Range(-90, 90)]
        public double Longitude { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace DublinBikes_Macintosh.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SeedData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DublinBikes_Macintosh.Data;
using DublinBikes_Macintosh.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System.Threading.Tasks;


namespace DublinBikes_Macintosh.Models
{
    public class SeedData
    {
       public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new DublinBikesContext(serviceProvider.GetRequiredService<DbContextOptions<DublinBikesContext>>()))
            {
                // Look for any movies.
                if (context.Bikes.Any())
                {
                    return;   // DB has been seeded
                }

                context.Bikes.AddRange(
                    new Bikes
                    {
                        Address = "86 Point Road",
                        Latitude = 53.34,
                        Longitude = -53.39,
                        Name = "SMITHFIELD NORTH",
                        Number = 56
                    },

                    new Bikes
                    {
                        Address = "99 Clonmel Street",
                        Latitude = 96.34,
                        Longitude = -6.39,
                        Name = "C STREET",
                        Number = 13
                    },

                    new Bikes
                    {
                        Address = "1bis Hanover Quay",
                        Latitude = 9.00,
                        Longitude = -53.39,
                        Name = "QUAY BIKES",
                        Number = 154
                    },

                    new Bikes
                    {
                        Address = "18 Earl Terrace",
                        Latitude = 29.46,
                        Longitude = -7.18,
                        Name = "EARL TERRACE",
                        Number = 48
                    }
                );
                context.SaveChanges();
            }
        }
     
    }
}

Controllers/DublinBikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DublinBikes_Macintosh.Data;
using DublinBikes_Macintosh.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DublinBikes_Macintosh.Controllers
{
    public class DublinBikesController : Controller
    {
        private readonly DublinBikesContext _context;

        public DublinBikesController(DublinBikesContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Bikes.ToListAsync());
        }

        // Get bike details (int id)
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bike = await _context.Bikes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bike == null)
            {
                return NotFound();
            }

            return View(bike);
        }

        // Get bike create 
        public IActionResult Create()
        {
            return View();
        }

        //POST: Bikes create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,Name,Address,Latitude,Longitude")] Bikes bikes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bikes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bikes);
        }

        // GET: Bike/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bikes = await _context.Bikes.FindAsync(id);
            if (bikes == null)
            {
                return NotFound();
            }
            return View(bikes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,Name,Address,Latitude,Longitude")] Bikes bikes)
        {
            if (id != bikes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bikes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BikeExists(bikes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bikes);
        }

        // GET: Bike/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bikes = await _context.Bikes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bikes == null)
            {
                return NotFound();
            }

            return View(bikes);
        }

        // POST: Bikes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bikes = await _context.Bikes.FindAsync(id);
            _context.Bikes.Remove(bikes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BikeExists(int id)
        {
            return _context.Bikes.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using DublinBikes_Macintosh.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DublinBikes_Macintosh.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult HomeBike()
        {
            return View();
        }

        public IActionResult Find()
        {
            return View();
        }
        public IActionResult Price()
        {
            return View();
        }
        public IActionResult Rent()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/DublinBikes/Create.cshtml
@model DublinBikes_Macintosh.Models.Bikes

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Bike</h4>
<hr />
<div class="row", style="width:400%">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DublinBikes/Delete.cshtml
@model DublinBikes_Macintosh.Models.Bikes

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bike</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/DublinBikes/Details.cshtml
@model DublinBikes_Macintosh.Models.Bikes

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Bike</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/DublinBikes/Edit.cshtml
@model DublinBikes_Macintosh.Models.Bikes

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>


<hr />
<div class="row", style="width:400%">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Number" />

            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DublinBikes/Index.cshtml
@model List<DublinBikes_Macintosh.Models.Bikes>
<body>
    <header>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="DublinBikes"
               asp-action="Create">Create</a>
        </li>
    </header>

    <table class="table" , style="width:100%">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model[0].Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model[0].Address)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>

Views/Home/Edit.cshtml
@model DublinBikes_Macintosh.Models.Bikes

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Bike</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Number" />

            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Find.cshtml
@{
    ViewData["Title"] = "Find";
}
<h1>
    How can you release a bike ?
</h1>
<p1>
    There are 2 ways of choosing and releasing a bike.
    You can release a bike at a station terminal. Select a bike from the terminal screen and release it by pressing the button on the bike stand as directed.
    <br />
    Alternatively, you can use the NOW TV dublinbikes App. Select the bike of your choice and swipe ‘release a bike’.
    You then have 60 seconds to release the bike chosen by pressing the button on the bike stand.
</p1>
<br />
<h2>
    No bike at the station ?
</h2>
<p2>
    You can view nearby stations and the number of available bikes at each station on the official NOW TV dublinbikes App or at a station terminal.
</p2>

Views/Home/HomeBike.cshtml
@{
    ViewData["Title"] = "Home Bike";
}
<h1>
    This is the Home Bike Page !
</h1>

Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="Views/Home/css" href="style.css">
    <title>DublinBikes</title>
</head>
<body>
    <!-- Header -->
    <section id="header">
        <div class="header container">
            <div class="nav-bar">
                <div class="brand">
                    <a href="#hero"><h1><span>D</span>ublin <span>B</span>ikes</h1></a>
                </div>
                <div class="nav-list">
                    <div class="hamburger"><div class="bar"></div></div>
                    <ul>
                        <li><a href="#hero" data-after="Home">Home</a></li>
                        <li><a href="#services" data-after="Service">Services</a></li>
                        <!--<li><a href="#projects" data-after="Projects">Projects</a></li>-->
                        <li><a href="#about" data-after="About">About</a></li>
                        <li><a href="#contact" data-after="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- End Header -->
    <!-- Hero Section  -->
    <section id="hero">
        <div class="hero container">
            <div>
                <h1>Welcome to<span></span></h1>
                <h1>Dublin <span></span></h1>
                <h1>Bikes <span></span></h1>
                <!--<a href="#projects" type="button" class="cta">Portfolio</a>-->
            </div>
        </div>
    </section>
    <!-- End Hero Section  -->
    <!-- Service Section -->
    <section id="services">
        <div class="services container">
            <div class="service-top">
                <h1 class="section-title">Serv<span>i</span>ces</h1>
                <p>Book your bikes on our website.</p>
            </div>
            <div class="service-bottom">
                <div class="service-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/services.png" /></div>
                    <h2>Facility</h2>
                    <p></p>
                </div>
                <div class="service-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/services.png" /></div>
                    <h2>Mobility</h2>
                    <p></p>
                </div>
                <div class="service-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/services.png" /></div>
                    <h2>Easy Access</h2>
                    <p></p>
                </div>
                <div class="service-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/services.png" /></div>
                    <h2>Reliable</h2>
                    <p></p>
                </div>
            </div>
        </div>
    </section>
    
   

    <!-- About Section -->
    <section id="about">
        <div class="about container">
            <div class="col-left">
                <div class="about-img">
                    <img src="./img/img-2.png" alt="img">
                </div>
            </div>
            <div class="col-right">
                <h1 class="section-title">About <span>us</span></h1>
                <h2>Make your life easier</h2>
                <p>Get a Dublin Bike</p>
                <!--<a href="#" class="cta"><button type="button" onclick="/DublinBikes/Index">Reserve Now</button></a>-->
                <form method="get" action="/DublinBikes/Index">
                    <a href="#" class="cta"><button type="submit"="/DublinBikes/Index">Reserve Now</button></a>
                    <!--  <button type="submit">Continue</button>-->
                </form>
            </div>
        </div>
    </section>
    <!-- End About Section -->
    <!-- Contact Section -->
    <section id="contact">
        <div class="contact container">
            <div><h1 class="section-title">Contact <span>info</span></h1></div>
            <div class="contact-items">
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/phone.png" /></div>
                    <div class="contact-info">
                        <h1>Phone</h1>
                        <h2>+33 6 51 13 39 89</h2>
                        <h2>+353 1 761 7835</h2>
                    </div>
                </div>
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/new-post.png" /></div>
                    <div class="contact-info">
                        <h1>Email</h1>
                        <h2>dublinbikes@gmail.com</h2>
                        <h2>acdc@gmail.com</h2>
                    </div>
                </div>
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/map-marker.png" /></div>
                    <div class="contact-info">
                        <h1>Address</h1>
                        <h2>Dublin</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Contact Section -->
    <!-- Footer -->
    <section id="footer">
        <div class="footer container">
            <div class="brand"><h1><span>D</span>ublin <span>B</span>ikes</h1></div>
            <h2>Dublin Bikes</h2>
            <div class="social-icon">
                <div class="social-item">
                    <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/facebook-new.png" /></a>
                </div>
                <div class="social-item">
                    <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/instagram-new.png" /></a>
                </div>
                <div class="social-item">
                    <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/twitter.png" /></a>
                </div>
                <div class="social-item">
                    <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/behance.png" /></a>
                </div>
            </div>
        </div>
    </section>
    <!-- End Footer -->
    <script src="./app.js"></script>
</body>
</html>

Views/Home/Price.cshtml
@{
    ViewData["Title"] = "Price";
}
<h1>
    <i>
        Subscription details !!
    </i>
</h1>
<h4>
    Annual Membership
</h4>
<p4>
    <b>
        € 0.80
    </b>
    For just €4.00 you can enjoy 5 rides
    that’s just 0.80cent per ride! Ideal for the occasional rider.
    A ride is 60 minutes in duration.
</p4>
<br />

<h2>
    3 Month Membership
</h2>
<p1>
    <b>
        € 20.00
    </b>
    Our 3 month membership plan is great value!
    Avail of up to four 60 minute rides per day.
    Perfect for students and seasonal riders.
</p1>
<br />
<h3>
    Annual Membership
</h3>
<p2>
    <b>
        € 75.00
    </b>
    Annual membership gives you access to Bikes up to 4 times a day 365 days per year!
    The ultimate commuter solution!
</p2>

Views/Home/Rent.cshtml
@{
    ViewData["Title"] = "Rent";
}
<h1>
    Log in and choose a NOW TV dublinbikes subscription
</h1>
<p1>
    You can create an account on the official NOW TV dublinbikes App or on dublinbikes.
    ie Short term subscriptions can also be chosen at credit card enabled stations.
    Tap the screen on ‘choose a NOW TV dublinbikes subscription’ and select 3 Day Ticket.
</p1>
<br />
<p2>
    Before selecting a bike you can consult previous users feedback on the App or on the bike terminal.
    Once selected the condition of the bike should be checked at the station.
    <br />
    The saddle, pedals, basket attachment, bell, brakes, lighting and tyre condition
    should all be checked in advance of taking the bike.
</p2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dublin Bikes App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Dublin Bikes App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>